### ISSUE TITLE
DT crashes in toneequal.c when built with GCC 11 and both -O2 -march=native and _OPENMP enabled

### ISSUE THREAD

**Issue by eternalinflation** [darktable-org/darktable#10498]
**To Reproduce**
1. Build darktable v3.6.1 with GCC 11.2.0 and flags `-march=native -O2` + `cmake ... -DUSE_OPENMP=yes ...`
2. Open Lighttable and click on any image to open in Darkroom
3. Go back to Lighttable and click another random image
4. See error - sometimes it requires two or three iterations to trigger the SIGSEGV. This happens regardless fresh profile or not.

**Error**
````
Thread 14 "worker res 0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc57fa640 (LWP 2114561)]
0x00007fffadd87b9f in pixel_correction.avx2.6.lto_priv.0 (exposure=<optimized out>, factors=0x555559b743f0, sigma=<optimized out>) at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/iop/toneequal.c:783
783         result += gaussian_func(expo - centers_ops[i], gauss_denom) * factors[i];
(gdb) bt
#0  0x00007fffadd87b9f in pixel_correction.avx2.6.lto_priv.0 (exposure=<optimized out>, factors=0x555559b743f0, sigma=<optimized out>)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/iop/toneequal.c:783
#1  0x00007fffadd5b994 in compute_lut_correction._omp_fn.0.avx2.6.lto_priv.0 ()
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/iop/toneequal.c:1430
#2  0x00007ffff77e1d76 in GOMP_parallel () at /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/libgomp.so.1
#3  0x00007fffadd80c93 in compute_lut_correction.avx2.7.lto_priv.0 (g=<optimized out>, offset=<optimized out>, scaling=<optimized out>)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/iop/toneequal.c:1421
#4  0x00007fffadd4899e in update_curve_lut (self=0x555557f60c60) at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/iop/toneequal.c:1475
#5  commit_params (self=0x555557f60c60, p1=<optimized out>, pipe=<optimized out>, piece=<optimized out>)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/iop/toneequal.c:1537
#6  0x00007ffff7d6734b in dt_iop_commit_params(dt_iop_module_t*, dt_iop_params_t*, dt_develop_blend_params_t*, dt_dev_pixelpipe_t*, dt_dev_pixelpipe_iop_t*)
    (module=0x555557f60c60, params=0x555558ad8b30, blendop_params=0x555558b0e4a0, pipe=0x55555661d800, piece=0x7fffb4047c70)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/develop/imageop.c:1768
#7  0x00007ffff7da5cb6 in dt_dev_pixelpipe_synch_all(dt_dev_pixelpipe_t*, dt_develop_t*) (pipe=0x55555661d800, dev=0x5555566fb800)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/develop/pixelpipe_hb.c:411
#8  0x00007ffff7da5e90 in dt_dev_pixelpipe_change(dt_dev_pixelpipe_t*, dt_develop_t*) (pipe=0x55555661d800, dev=0x5555566fb800)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/develop/pixelpipe_hb.c:458
#9  0x00007ffff7d52a91 in dt_dev_process_image_job(dt_develop_t*) (dev=0x5555566fb800)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/develop/develop.c:575
#10 0x00007ffff7cc7911 in dt_dev_process_image_job_run(dt_job_t*) (job=<optimized out>)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/control/jobs/develop_jobs.c:55
#11 0x00007ffff7cbdfbb in dt_control_run_job_res (res=0, control=0x5555555985f0)
    at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/control/jobs.c:215
#12 dt_control_work_res(void*) (ptr=<optimized out>) at /usr/src/debug/media-gfx/darktable-3.6.1-r2/darktable-3.6.1/src/control/jobs.c:519
#13 0x00007ffff794ce3e in start_thread () at /lib64/libpthread.so.0
#14 0x00007ffff7a5d2df in clone () at /lib64/libc.so.6
````

**Platform**
````
processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Xeon(R) CPU E3-1225 v5 @ 3.30GHz
stepping        : 3
microcode       : 0xea
````

* darktable version : 3.6.1
* OS                : Linux
* Linux - Distro    : Gentoo
* Memory            : 64G
* Graphics card     : i965
* Graphics driver   : intel
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              : happens under both Xorg and Wayland
* GTK+              : gtk+-3.24.29
* gcc               : 11.2.0
* cflags            : `-O2 -pipe -march=native -flto -ggdb -msse3`
* CMAKE_BUILD_TYPE  : Release

**This issue cannot be reproduced with**
- gcc 10.3.0
- gcc 11.2.0 and _either_ `_OPENMP` _or_ `-O2 -march=native` _disabled_
- gcc 11.2.0 and optimzation `-O1` or lower together with `_OPENMP`

**Comment by paolodepetrillo** [comment]
This may be fixed already in master:
https://github.com/darktable-org/darktable/pull/10211

**Comment by eternalinflation** [comment]
@paolodepetrillo - It is indeed! Thanks so much, great job! 
I'd suggest to cherry-pick this commit for the next release.

**Comment by TurboGit** [comment]
> I'd suggest to cherry-pick this commit for the next release.

Not needed since next release is being prepared from master.
