### ISSUE TITLE
seg fault when updating title metadata

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10619]
I'm currently editing metadata for a large number of images on latest master (3.7.0+1668~g33e0bc308). Eventually, but not always, I get a seg fault while editing the title field.

I currently have two collect rules (film roll=WIP AND title=not defined) though I'm not sure how much relevance that has.

gdb backtrace says

```
Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
dt_image_synch_xmps (img=img@entry=0x555558f13140 = {...}) at /srv/local/coding/darktable-working/src/common/image.c:2468
2468	void dt_image_synch_xmps(const GList *img)
(gdb) bt
#0  dt_image_synch_xmps (img=img@entry=0x555558f13140 = {...}) at /srv/local/coding/darktable-working/src/common/image.c:2468
#1  0x00007fffa00121f7 in _write_metadata (self=0x555558785c80) at /srv/local/coding/darktable-working/src/libs/metadata.c:250
#2  0x00007fffa0012306 in _key_pressed (textview=0x555558569490, event=0x555558d120e0, self=0x555558785c80) at /srv/local/coding/darktable-working/src/libs/metadata.c:281
#3  0x00007ffff6a70f38 in  () at /usr/lib/libgtk-3.so.0
#4  0x00007ffff6417d8f in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff6433718 in  () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff643440b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff6435330 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff6d27b15 in  () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff7c50a3a in dt_shortcut_dispatcher (user_data=<optimized out>, event=0x555558d120e0, w=0x5555579002a0) at /srv/local/coding/darktable-working/src/gui/accelerators.c:3456
#10 dt_shortcut_dispatcher (w=0x5555579002a0, event=0x555558d120e0, user_data=<optimized out>) at /srv/local/coding/darktable-working/src/gui/accelerators.c:3431
#11 0x00007ffff6a70f38 in  () at /usr/lib/libgtk-3.so.0
#12 0x00007ffff6417d8f in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff6433718 in  () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff643440b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff6435330 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff6d279ba in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff6bc8aa2 in  () at /usr/lib/libgtk-3.so.0
#18 0x00007ffff6bc98f3 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff6933643 in  () at /usr/lib/libgdk-3.so.0
#20 0x00007ffff697ea24 in  () at /usr/lib/libgdk-3.so.0
#21 0x00007ffff71ec4dc in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff7240799 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff71eba63 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff6bbf88f in gtk_main () at /usr/lib/libgtk-3.so.0
#25 0x00007ffff7c56019 in dt_gui_gtk_run (gui=<optimized out>) at /srv/local/coding/darktable-working/src/gui/gtk.c:1385
#26 0x0000555555555090 in main (argc=<optimized out>, argv=<optimized out>) at /srv/local/coding/darktable-working/src/main.c:93
```

Given that I'm building master pretty regularly I tried reverting 33e0bc3 and I could no longer reproduce the issue after doing so.

**Comment by elstoc** [comment]
Ping @AlicVB

**Comment by AlicVB** [comment]
Fair enough :)
@turbogit better revert the commit indeed... it seems to be the cause of #10625 too :(

But we considering the change done in the commit, I fear that it hides a more important issue...
My best idea would be that there's some concurrency access problem with this function especially when we ask for different type of list. Currently the fact that we directly return the cached list in any case "hides" the issue because it's very quick, but with my change, that slow down things a little bit and may show the issue even more...

But fixing that is imho too "delicate" so close of the release... @TurboGit : what do you think ?

**Comment by elstoc** [comment]
I'm sure we could consider something for 3.8.1 once any fix has had a bit of field testing in master.

**Comment by AlicVB** [comment]
@elstoc :  I suppose we can close this now...

**Comment by elstoc** [comment]
Yep I've just tagged a few dozen in master without issue.

**Comment by TurboGit** [comment]
Yes, 3.8.1 but too late for 3.8 at this stage.
