### ISSUE TITLE
Dragging from the thumbnail view in darkroom mode to the main image crashes darktable

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#10842]
I didn't even know this was possible. This is latest dt git. Accidentally didn't let go of the image selection under the main image I was currently editing and dragged the thumbnail into the image. This lead to a crash. Backtrace as follows:

```
Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
dt_thumbtable_event_dnd_received (widget=<optimized out>, context=0x555558a83460, x=<optimized out>, y=<optimized out>, selection_data=0x7fffffffe2b0, target_type=<optimized out>, time=56450883, user_data=0x0) at /home/panda/Downloads/dtcompile/darktable/src/dtgtk/thumbtable.c:1730
1730	    if(table->drag_list)
(gdb) bt full
#0  dt_thumbtable_event_dnd_received
    (widget=<optimized out>, context=0x555558a83460, x=<optimized out>, y=<optimized out>, selection_data=0x7fffffffe2b0, target_type=<optimized out>, time=56450883, user_data=0x0)
    at /home/panda/Downloads/dtcompile/darktable/src/dtgtk/thumbtable.c:1730
        table = 0x0
        success = 0
#1  0x00007ffff6a6a9fc in  () at /usr/lib/libgtk-3.so.0
#2  0x00007ffff64141c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff641455a in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff6d482a1 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff6a68cf7 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff64141c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff641455a in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff6c4d4b6 in gtk_selection_convert () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff6d4b1bc in  () at /usr/lib/libgtk-3.so.0
#10 0x00007ffff6bbde9f in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#11 0x00007ffff6926643 in  () at /usr/lib/libgdk-3.so.0
#12 0x00007ffff6972ca4 in  () at /usr/lib/libgdk-3.so.0
#13 0x00007ffff71e152c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff72357b9 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff71e0ab3 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff6bb393f in gtk_main () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff7c55ad9 in dt_gui_gtk_run (gui=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/panda/Downloads/dtcompile/darktable/src/gui/gtk.c:1385
        widget = <optimized out>
        allocation = {x = 0, y = 0, width = 566, height = 466}
#18 0x0000555555555090 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/panda/Downloads/dtcompile/darktable/src/main.c:93
```

**Comment by piratenpanda** [comment]
Should this open the dragged image or should it be impossible to drag and drop from there?

**Comment by phweyland** [comment]
> I didn't even know this was possible.

This is not possible. Darkroom takes the new image as soon as you click on the thumbnail. The subsequent drag&drop does (should do) nothing.
