### ISSUE TITLE
Segmentation faults when using the crop module / latest git

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#12413]
I just compiled latest git and I noticed two things. The first time you copy changes to another image the thumbtable scrolls to the bottom. Happened twice to me now. But I also get the following segmentation fault when using crop:

```Thread 126 "worker res 1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff38a8c6c0 (LWP 13295)]
0x00007fff70292c32 in _copy_output._omp_fn.0 () at /home/panda/Downloads/dtcompile/darktable/src/iop/gamma.c:305
305	      out[j + 2 - c] = (uint8_t)(fminf(fmaxf(roundf(255.0f * in[j + c]), 0.0f), 255.0f));
(gdb) bt full
#0  0x00007fff70292c32 in _copy_output._omp_fn.0 ()
    at /home/panda/Downloads/dtcompile/darktable/src/iop/gamma.c:305
        c = 0
        j = 3866560
        buffsize = <optimized out>
        out = 0x7fff3f55e040 "wjO>wjO>wjO>wjO>wjO>vjO>vjO>vjO>vjP>vkQ>wkQ>vkQ>vkR>vkR>vkR>vkR>vkR>vkR>vkR>vkR>vkR>vkR>vkS>vkS>vkS>vkS>vkS>ukS>vkS>vkS>vkT>vkT>vkT>ukT>ukT>ukT>ukT>ukT>ukT>ukU>ukU>ukU>ukU>ukU>ukU>ukU>ukU>ukU>ujU>ukU>"...
        in = 0x7fff21941040
        mask_display = <optimized out>
        fcolor = <optimized out>
        buffsize = <optimized out>
        alpha = <optimized out>
#1  0x00007ffff7325406 in gomp_thread_start (xdata=<optimized out>)
    at /usr/src/debug/gcc/libgomp/team.c:129
        team = 0x7fffb0021340
        task = 0x7fffb0021b08
        data = <optimized out>
        pool = 0x7fffb0021220
        local_fn = 0x7fff70292b70 <_copy_output._omp_fn.0>
        local_data = 0x7fffc5feb710
#2  0x00007ffff209f78d in  () at /usr/lib/libc.so.6
#3  0x00007ffff21208e4 in clone () at /usr/lib/libc.so.6
```

I don't know if it's the crop module at all but it happens frequently. Might be some AMD OpenCL thingie again? @jenshannoschwalm

**Comment by jenshannoschwalm** [comment]
Haven't seen this once. Just to make sure, doesn't happen with CL disabled?

Also there is a late fix from Yesterday about pixel pipe cache... Make sure thats included.

**Comment by piratenpanda** [comment]
Seems I didn't have all commits as git clean -x -d -f and pull --rebase fetched a few changes. I'll test and report back in case it appears again, sorry for the noise
