### ISSUE TITLE
segfault when upscaling images

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#13421]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Darktable will segfault when upscaling an image, or even simply when upscaling is allowed. This can occur during export, as well as during printing (which uses the export pipeline).

**To Reproduce**
1. Import an image
2. In export
a. reset the export lib (if not already a fresh config)
b. set size  to "by scale (for file)" (for convenience of reproduction for arbitrary images sizes)
c. in the next text box, set scale factor to any number > 1
d. set "allow upscaling" to "yes"
4. Select the image and hit "export"
5. darktable will work for a bit then segfault

_alternative cli invocation_

```
darktable-cli PATH_TO_IMAGE /tmp/exported.jpg  --width NUM_LARGER_THAN_IMAGE_WIDTH --upscale true
```

_minimal cli invocation_

```
darktable-cli PATH_TO_IMAGE /tmp/exported.jpg --upscale true
```

Note that in this case it appears that it isn't even necessary to force upscaling via a `--width` argument.

**Expected behavior**
The image will be exported upscaled.

**Which commit introduced the error**
fe309e6c8b695eae204fa5637b33e051a8b4d5b4

But is this commit is actually bad? Or could fixing the cache behavior have exposed another bug? 

**Platform**

* darktable version : 4.3.0+301~gecd8a47312
* OS : Linux 6.0
* Linux - Distro : Debian testing
* Memory : 32GB
* Graphics card : GeForce RTX 3080 Mobile
* Graphics driver : Nvidia 510.108.03
* OpenCL installed : yes
* OpenCL activated : yes
* Xorg : 7.7
* Desktop : Gnome
* GTK+ : 3.24.36
* gcc : 12.2.0
* cflags :
* CMAKE_BUILD_TYPE : Release

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **yes**
   - What lua scripts start automatically? **none**
   - What lua scripts were running when the bug occurred? **none**
 - This occurs if conf `codepaths/openmp_simd=true` as well as with the default `codepaths/openmp_simd=false`, though in different functions

**Backtraces**

I don't get a backtrace from the segfault when running darktable, but instead just a core dump. I can see a backtrace via gdb, though. Here is gdb output when running `darktable-cli`

```
Thread 35 "darktable-cli" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff1dff7240 (LWP 1562909)]
.omp_outlined._debug__.17 (roi_out=0x7fffffff5a60, in_stride=<optimized out>, out=<optimized out>, out_stride=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, in=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>) at /home/dtorop/src/darktable/src/common/interpolation.c:1682
1682	      _mm_stream_ps(o, vs);
(gdb) bt
#0  .omp_outlined._debug__.17
    (roi_out=0x7fffffff5a60, in_stride=<optimized out>, out=<optimized out>, out_stride=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, in=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>)
    at /home/dtorop/src/darktable/src/common/interpolation.c:1682
#1  .omp_outlined..18
    (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, roi_out=0x7fffffff5a60, vmeta=@0x7fffffff59c8: 0x5555581c03a8, vlength=@0x7fffffff59b8: 0x5555581adf00, hlength=@0x7fffffff59c0: 0x7fff48019040, in=<optimized out>, in_stride=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>, out=<optimized out>, out_stride=<optimized out>) at /home/dtorop/src/darktable/src/common/interpolation.c:1620
#2  0x00007ffff784d5a3 in __kmp_invoke_microtask ()
    at /usr/lib/llvm-14/lib/libomp.so.5
#3  0x00007ffff77c1329 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#4  0x00007ffff77bfbc2 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#5  0x00007ffff78277cb in  () at /usr/lib/llvm-14/lib/libomp.so.5
#6  0x00007ffff164cfd4 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#7  0x00007ffff16cd66c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

And here is gdb output with a similar invocation using the OpenMP code (via `--conf codepaths/openmp_simd=true`)

```
Thread 33 "darktable-cli" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff22ffb140 (LWP 1563881)]
0x00007ffff7b0a5a0 in .omp_outlined._debug__.13 (roi_out=<optimized out>, in_stride_floats=<optimized out>, in=0x7fff4a3de040, out_stride_floats=<optimized out>, out=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>) at /home/dtorop/src/darktable/src/common/interpolation.c:1519
1519	      for_each_channel(c, aligned(vs:16)) out[baseidx + c] = fmaxf(vs[c], 0.f);
(gdb) bt
#0  0x00007ffff7b0a5a0 in .omp_outlined._debug__.13
    (roi_out=<optimized out>, in_stride_floats=<optimized out>, in=0x7fff4a3de040, out_stride_floats=<optimized out>, out=<optimized out>, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, vindex=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, vkernel=<optimized out>)
    at /home/dtorop/src/darktable/src/common/interpolation.c:1519
#1  .omp_outlined..14
    (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, roi_out=<optimized out>, vmeta=<optimized out>, vlength=<optimized out>, hlength=<optimized out>, vindex=<optimized out>, in_stride_floats=<optimized out>, hindex=<optimized out>, hkernel=<optimized out>, in=<optimized out>, vkernel=<optimized out>, out_stride_floats=<optimized out>, out=<optimized out>)
    at /home/dtorop/src/darktable/src/common/interpolation.c:1458
#2  0x00007ffff784d5a3 in __kmp_invoke_microtask ()
    at /usr/lib/llvm-14/lib/libomp.so.5
#3  0x00007ffff77c1329 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#4  0x00007ffff77bfbc2 in  () at /usr/lib/llvm-14/lib/libomp.so.5
#5  0x00007ffff78277cb in  () at /usr/lib/llvm-14/lib/libomp.so.5
#6  0x00007ffff164cfd4 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#7  0x00007ffff16cd66c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by dtorop** [comment]
Ah! It does appear to be a cache issue. It looks like export expects the cache buffers to never change size, but they need to increase in the event of finalscale scaling up the image. Prior to fe309e6c8b695eae204fa5637b33e051a8b4d5b4, the pixelpipe cache buffer could be rescaled, but in current code the assumption is that it is always large enough.

I'll make a PR with a fix for this.

I'm still curious why, when upscaling is allowed, the image is scaled up, even if the end result isn't. See for example this output of my test bugfixed version:

```
$ darktable-cli /tmp/dark\ grey.png /tmp/exported.jpg --upscale true --core --configdir /tmp/dt/conf --cachedir /tmp/dt/cache --conf codepaths/openmp_simd=true -d pipe -d verbose -d imageio
output file already exists, it will get renamed
[dt_codepaths_init] will be using experimental plain OpenMP SIMD codepath.
[dt_imageio_export_with_flags] 
 colorin colorout finalscale gamma (4)
     1.7117 [dt_imageio_export] [export] imgid 1, 1280x720 --> 2560x1440 (scale 2.000000). upscale=yes, hq=yes
     1.7118 [modify roi IN]              [export]       finalscale           (   0/   0) 1280x 720 scale=1.0000 --> (   0/   0) 2560x1440 scale=2.0000 
     1.7118 [pixelpipe full]             [export]                            (   0/   0) 1280x 720 scale=1.0000 --> (   0/   0) 1280x 720 scale=1.0000 
     1.7119 [pixelpipe_cache_get]        [export]       colorin                             line  1, age    2 at 0x7fe7b4dcc040. hash  18446744073709551615, basic  18446744073709551615
     1.7119 [pixelpipe_process_on_CPU]   [export]       colorin              (   0/   0) 1280x 720 scale=1.0000 --> (   0/   0) 1280x 720 scale=1.0000 
     1.7168 [pixelpipe_cache_get]        [export]       colorout                            line  0, age    3 at 0x7fe7b5bdd040. hash  18446744073709551615, basic  18446744073709551615
     1.7168 [pixelpipe_process_on_CPU]   [export]       colorout             (   0/   0) 1280x 720 scale=1.0000 --> (   0/   0) 1280x 720 scale=1.0000 
     1.7201 [pixelpipe_cache_get]        [export]       finalscale            new           line  1, age    2 at 0x7fe7687bf040. hash    432763395586903365, basic  17935309880948213357
     1.7203 [pixelpipe_process_on_CPU]   [export]       finalscale           (   0/   0) 1280x 720 scale=1.0000 --> (   0/   0) 2560x1440 scale=2.0000 
     1.7204 [clip_and_zoom_roi]          [export]       finalscale           (   0/   0) 1280x 720 scale=1.0000 --> (   0/   0) 2560x1440 scale=2.0000 
     1.7489 [cache report]               [export]                             2 lines (important=0, used=2). Used 70MB, limit=0MB. Hitrate=0.00
[export_job] exported to `/tmp/exported_14.jpg'
$ identify /tmp/dark\ grey.png /tmp/exported.jpg 
/tmp/dark grey.png PNG 1280x720 1280x720+0+0 8-bit sRGB 4236B 0.000u 0:00.000
/tmp/exported.jpg JPEG 1280x720 1280x720+0+0 8-bit sRGB 24627B 0.000u 0:00.000
$ 
```

**Comment by TurboGit** [comment]
Probably related to the regression test suite issue:

```
$ ./run.sh 0018-perspective-corr/
Test 0018-perspective-corr
      Image mire1.cr2
./run.sh: line 257: 1474157 Segmentation fault      $CLI --width 2048 --height 2048 --hq true --apply-custom-presets false "$TEST_IMAGES/$IMAGE" "$TEST.xmp" output.png --core --disable-opencl $CORE_OPTIONS > /dev/null 2> /dev/null
  FAILS : darktable-cli errored
```

I was about to report. I'll test the fix.
