### ISSUE TITLE
crash when importing image

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#16455]
### Describe the bug

Import the raw and XMP from https://discuss.pixls.us/t/display-softproof-export-color-mismatch-troubleshooting/42516/13. Darktable crashes immediately. I did not find a stack trace / core dump.
[dt-clean-config-and-db-no-opencl.log](https://github.com/darktable-org/darktable/files/14593021/dt-clean-config-and-db-no-opencl.log)

With / without OpenCL, the same. Release or RelWithDebInfo build, the same. Crashes with clean config + DB, too.
[dt-clean-config-and-db-no-opencl.log](https://github.com/darktable-org/darktable/files/14593028/dt-clean-config-and-db-no-opencl.log)

When darktable is restarted, the image is in the DB with a default stack.

Should be a recent change (haven't bisected yet), as it used to work with 4.7.0+693~g2a57b25fe3.

I've attached the output from `-d all -d verbose`, for lack of anything better.

### Steps to reproduce

Import the raw and XMP from https://discuss.pixls.us/t/display-softproof-export-color-mismatch-troubleshooting/42516/13. 

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+739~gde5c50e3b3

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6GB, 525.147.05

**Comment by piratenpanda** [comment]
here's what I get from gdb

```
bt full
#0  sqlite3_finalize (pStmt=0x7fffa4011b70) at /usr/src/debug/sqlite/sqlite-src-3450200/sqlite3.c:89984
        v = 0x7fffa4011b70
        db = 0x7ff85a9c47c1
        rc = <optimized out>
#1  0x00007ffff79221b5 in dt_exif_xmp_read
    (img=img@entry=0x7fffa56445f0, filename=filename@entry=0x7fffd33ef7f0 "/home/panda/sync/Bilder2/2023.09.24_Margarita/_51A4224.CR3.xmp", history_only=history_only@entry=0)
    at /home/panda/Downloads/darktable/src/common/exif.cc:4073
        xmpData = <optimized out>
        stmt = 0x7fffa4011b70
        iop_order_list = 0x7fffa5659d20 = {0x7fffa566cbf0, 0x7fffa566afe0, 0x7fffa567bd30, 0x7fffa569fa80, 0x7fffa567bee0, 0x7fffa564d9a0, 0x7fffa567f160, 0x7fffa5660910, 0x7fffa56815b0, 0x7fffa567ff40, 0x7fffa564a610, 0x7fffa564a370, 0x7fffa563cfd0, 0x7fffa5658f00, 0x7fffa567bc30, 0x7fffa5654980, 0x7fffa5655020, 0x7fffa5680820, 0x7fffa514f930, 0x7fffa5681e70, 0x7fffa5686bd0, 0x7fffa566d000, 0x7fffa567fa80, 0x7fffa5646560, 0x7fffa56464a0, 0x7fffa5646380, 0x7fffa5680910, 0x7fffa56544a0, 0x7fffa563d3b0, 0x7fffa564d920, 0x7fffa5651430, 0x7fffa5663aa0, 0x7fffa5654b90, 0x7fffa5680a50, 0x7fffa5658bf0, 0x7fffa5651860, 0x7fffa568d1e0, 0x7fffa5682db0, 0x7fffa5682e00, 0x7fffa5642580, 0x7fffa56425d0, 0x7fffa56511d0, 0x7fffa5651220, 0x7fffa5655820, 0x7fffa5655870, 0x7fffa567be20, 0x7fffa567be70, 0x7fffa5636f20, 0x7fffa5636f90, 0x7fffa5648460, 0x7fffa56484b0, 0x7fffa5642bf0, 0x7fffa5642c60, 0x7fffa5680340, 0x7fffa5680390, 0x7fffa56461f0, 0x7fffa5646260, 0x7fffa567cbd0, 0x7fffa567cc20, 0x7fffa40083d0, 0x7fffa4008440, 0x7fffa569f240, 0x7fffa569f290, 0x7fffa5606d70, 0x7fffa5606de0, 0x7fffa56869b0, 0x7fffa5686a20, 0x7fffa5642ad0, 0x7fffa5642b40, 0x7fffa4e80690, 0x7fffa4e80700, 0x7fffa5642670, 0x7fffa56426c0, 0x7fffa5642730, 0x7fffa567f1b0, 0x7fffa567f200, 0x7fffa567f270, 0x7fffa566ce50, 0x7fffa566cea0, 0x7fffa566cf10, 0x7fffa566e590, 0x7fffa566e5e0, 0x7fffa566e650, 0x7fffa5646980, 0x7fffa56469d0, 0x7fffa5646a40, 0x7fffa56512b0, 0x7fffa5651300, 0x7fffa5651370, 0x7fffa5675b80}
        history_entries = 0x7fffa56618e0 = {0x7fffa5675eb0, 0x7fffa5675f20, 0x7fffa5642060, 0x7fffa5642110, 0x7fffa564d760, 0x7fffa564d830, 0x7fffa56867d0, 0x7fffa56868a0, 0x7fffa569fb60, 0x7fffa569fc30, 0x7fffa565e2d0}
        has_highlights = <optimized out>
        has_rawprepare = <optimized out>
        iop_order_version = <optimized out>
        num_masks = <optimized out>
        preset_applied = 1
        mask_entries = <optimized out>
        num = <optimized out>
        image = std::unique_ptr<Exiv2::Image> = {get() = 0x7fffa5682870}
        mask_entries_v3 = <optimized out>
        all_ok = 1
        add_to_history_end = <optimized out>
        pos = Python Exception <class 'gdb.error'>: value has been optimized out

        xmp_version = <optimized out>
        c = <optimized out>
        __FUNCTION__ = "dt_exif_xmp_read"
#2  0x00007ffff7944707 in _image_import_internal
    (film_id=film_id@entry=6, filename=filename@entry=0x7fffa56263a0 "/home/panda/sync/Bilder2/2023.09.24_Margarita/_51A4224.CR3", override_ignore_nonraws=override_ignore_nonraws@entry=0, lua_locking=lua_locking@entry=1, raise_signals=raise_signals@entry=0) at /home/panda/Downloads/darktable/src/common/image.c:1955
        normalized_filename = 0x7fffa565cf50 "/home/panda/sync/Bilder2/2023.09.24_Margarita/_51A4224.CR3"
        cc = <optimized out>
        ext = 0x7fffa565aee0 "cr3"
        supported = 1
        rc = <optimized out>
        stmt = 0x7fffa4011b70
        imgfname = 0x7fffa56354a0 "_51A4224.CR3"
        id = 76314
        __FUNCTION__ = "_image_import_internal"
        flags = <optimized out>
        extension = <optimized out>
        extra_file = <optimized out>
        basename = 0x7fffa5635f20 "_51A4224"
        cc2 = <optimized out>
        sql_pattern = 0x7fffa5663500 "_51A4224.%"
        group_id = <optimized out>
        img = 0x7fffa56445f0
        dtfilename = "/home/panda/sync/Bilder2/2023.09.24_Margarita/_51A4224.CR3.xmp", '\000' <repeats 4033 times>
        res = <optimized out>
        nb_xmp = <optimized out>
        tagid = 1435224552
        tagname = "\000\000\000\000\000\000\000\000p\024h\245\377\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000E`\353\361\377\177\000\000\000\000\000\000\000\000\001P@\004\000\000\000\000\000\0000\000\000\244\377\177\000\000@\004\000\000\000\000\000\0000Xh\245\377\177\000\000\bs\353\361\377\177\000\0000\000\000\244\377\177\000\000\000\000\000\000\000\000\000\000p\004?\323\377\177\000\000\001\000\000\000\000\000\000\000\000Th\245\377\177\000\000iv\353\361\377\177\000\000\000Th\245\377\177\000\000\223\236\353\361\377\177\000\000\310Wh\245\377\177\000\000p\024h\245\377\177\000\000\370\035\377\377\377\377\377\377\002\000\000\000\000\000\000\000p\004?\323\377\177\000\000"...
--Type <RET> for more, q to quit, c to continue without paging--
        L = <optimized out>
#3  0x00007ffff794535d in dt_image_import
    (film_id=film_id@entry=6, filename=filename@entry=0x7fffa56263a0 "/home/panda/sync/Bilder2/2023.09.24_Margarita/_51A4224.CR3", override_ignore_nonraws=override_ignore_nonraws@entry=0, raise_signals=raise_signals@entry=0) at /home/panda/Downloads/darktable/src/common/image.c:2068
#4  0x00007ffff79b062c in _control_import_image_insitu (update_interval=<synthetic pointer>, last_update=<synthetic pointer>, imgs=<synthetic pointer>, filename=<optimized out>)
    at /home/panda/Downloads/darktable/src/control/jobs/control_jobs.c:2404
        dirname = 0x7fffa564b820 "/home/panda/sync/Bilder2/2023.09.24_Margarita"
        film = {id = 6, dirname = "/home/panda/sync/Bilder2/2023.09.24_Margarita\000\000\000\000\000\000\000\032", '\000' <repeats 23 times>, "\220+\000\000\000\000\000\000\3400_\245\377\177\000\000\016\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\022", '\000' <repeats 15 times>, "\360Ka\245\377\177\000\000\265La\245\377\177\000\000\005\000\000\000\000\000\000\000\020La\245\377\177\000\000\001\000\000\000\000\000\000\000\002", '\000' <repeats 23 times>, "\220+\000\000\000\000\000\000\3400_\245"..., images_mutex = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x4141414141414141, __next = 0x4141414141414141}}, __size = '\000' <repeats 24 times>, 'A' <repeats 16 times>, __align = 0}}, dir = 0x4141414141414141, num_images = 1094795585, last_loaded = 0, ref = 0}
        filmid = 6
        imgid = <optimized out>
        dirname = <optimized out>
        film = {id = <optimized out>, dirname = {<optimized out> <repeats 512 times>}, images_mutex = {mutex = {__data = {__lock = <optimized out>, __count = <optimized out>, __owner = <optimized out>, __nusers = <optimized out>, __kind = <optimized out>, __spins = <optimized out>, __elision = <optimized out>, __list = {__prev = <optimized out>, __next = <optimized out>}}, __size = {<optimized out> <repeats 40 times>}, __align = <optimized out>}}, dir = <optimized out>, num_images = <optimized out>, last_loaded = <optimized out>, ref = <optimized out>}
        filmid = <optimized out>
        imgid = <optimized out>
#5  _control_import_job_run (job=0x555559109650) at /home/panda/Downloads/darktable/src/control/jobs/control_jobs.c:2528
        currtime = <optimized out>
        img = 0x7fffa4f38470 = {0x7fffa56263a0, 0x7fffa56263f0, 0x7fffa5626440, 0x7fffa5626490, 0x7fffa56264e0, 0x7fffa5626530, 0x7fffa5626580, 0x7fffa56265d0, 0x7fffa5626640, 0x7fffa56266b0, 0x7fffa5626720, 0x7fffa5626790, 0x7fffa5626800, 0x7fffa5626870, 0x7fffa56268e0, 0x7fffa5626950, 0x7fffa56269c0, 0x7fffa5626a30, 0x7fffa5626aa0, 0x7fffa5626b10, 0x7fffa5626b80, 0x7fffa5626bf0, 0x7fffa5626c60, 0x7fffa5626cd0, 0x7fffa5626d40, 0x7fffa5626db0, 0x7fffa5626e20, 0x7fffa5626e90, 0x7fffa5626f00, 0x7fffa5626f70, 0x7fffa5626fe0, 0x7fffa5627050, 0x7fffa56270c0, 0x7fffa5627130, 0x7fffa56271a0, 0x7fffa5627210, 0x7fffa5627280, 0x7fffa56272f0, 0x7fffa5627360, 0x7fffa56273d0, 0x7fffa5627440, 0x7fffa56274b0, 0x7fffa5627520, 0x7fffa5627590, 0x7fffa5627600, 0x7fffa5627670, 0x7fffa56276e0, 0x7fffa5627750, 0x7fffa56277c0, 0x7fffa5627830, 0x7fffa56278a0, 0x7fffa5627910, 0x7fffa5627980, 0x7fffa56279f0, 0x7fffa5627a60, 0x7fffa5627ad0, 0x7fffa5627b40, 0x7fffa5627bb0, 0x7fffa5627c20, 0x7fffa5627c90, 0x7fffa5627d00, 0x7fffa5627d70, 0x7fffa5627de0, 0x7fffa5627e50, 0x7fffa5627ec0, 0x7fffa5627f30, 0x7fffa5627fa0, 0x7fffa5628010, 0x7fffa5628080, 0x7fffa56280f0, 0x7fffa5628160, 0x7fffa56281d0, 0x7fffa5628240, 0x7fffa56282b0, 0x7fffa5628320, 0x7fffa5628390, 0x7fffa5628400, 0x7fffa5628470, 0x7fffa56284e0, 0x7fffa5628550, 0x7fffa56285c0, 0x7fffa5628630, 0x7fffa56286a0, 0x7fffa5628710, 0x7fffa5628780, 0x7fffa56287f0, 0x7fffa5628860, 0x7fffa56288d0, 0x7fffa5628940, 0x7fffa56289b0, 0x7fffa5628a20, 0x7fffa5628a90, 0x7fffa5628b00, 0x7fffa5628b70, 0x7fffa5628be0, 0x7fffa5628c50, 0x7fffa5628cc0, 0x7fffa5628d30, 0x7fffa5628da0, 0x7fffa5628e10, 0x7fffa5628e80, 0x7fffa5628ef0, 0x7fffa5628f60, 0x7fffa5628fd0, 0x7fffa5629040, 0x7fffa56290b0, 0x7fffa5629120, 0x7fffa5629190, 0x7fffa5629200, 0x7fffa5629270, 0x7fffa56292e0, 0x7fffa5629350, 0x7fffa56293c0, 0x7fffa5629430, 0x7fffa56294a0, 0x7fffa5629510, 0x7fffa5629580, 0x7fffa56295f0, 0x7fffa5629660, 0x7fffa56296d0, 0x7fffa5629740, 0x7fffa56297b0, 0x7fffa5629820, 0x7fffa5629890, 0x7fffa5629900, 0x7fffa5629970, 0x7fffa56299e0, 0x7fffa5629a50, 0x7fffa5629ac0, 0x7fffa5629b30, 0x7fffa5629ba0, 0x7fffa5629c10, 0x7fffa5629c80, 0x7fffa5629cf0, 0x7fffa5629d60, 0x7fffa5629dd0, 0x7fffa5629e40, 0x7fffa5629eb0, 0x7fffa5629f20, 0x7fffa5629f90, 0x7fffa562a000, 0x7fffa562a070, 0x7fffa562a0e0, 0x7fffa562a150, 0x7fffa562a1c0, 0x7fffa562a230, 0x7fffa562a2a0, 0x7fffa562a310, 0x7fffa562a380, 0x7fffa562a3f0, 0x7fffa562a460, 0x7fffa562a4d0, 0x7fffa562a540, 0x7fffa562a5b0, 0x7fffa562a620, 0x7fffa562a690, 0x7fffa562a700, 0x7fffa562a770, 0x7fffa562a7e0, 0x7fffa562a850, 0x7fffa562a8c0, 0x7fffa562a930, 0x7fffa562a9a0, 0x7fffa562aa10, 0x7fffa562aa80, 0x7fffa562aaf0, 0x7fffa562ab60, 0x7fffa562abd0, 0x7fffa562ac40, 0x7fffa562acb0, 0x7fffa562ad20, 0x7fffa562ad90, 0x7fffa562ae00, 0x7fffa562ae70, 0x7fffa562aee0, 0x7fffa562af50, 0x7fffa562afc0, 0x7fffa562b030, 0x7fffa562b0a0, 0x7fffa562b110, 0x7fffa562b180, 0x7fffa562b1f0, 0x7fffa562b260, 0x7fffa562b2d0, 0x7fffa562b340, 0x7fffa562b3b0, 0x7fffa562b420, 0x7fffa562b490, 0x7fffa562b500, 0x7fffa562b570, 0x7fffa562b5e0, 0x7fffa562b650, 0x7fffa562b6c0, 0x7fffa562b730, 0x7fffa562b7a0, 0x7fffa562b810, 0x7fffa562b880, 0x7fffa562b8f0, 0x7fffa562b960, 0x7fffa562b9d0...}
        params = <optimized out>
        data = 0x5555590df6e0
        cntr = 15
        message = "Importiere 3/512 Bilder", '\000' <repeats 488 times>
        t = <optimized out>
        total = 512
        imgs = 0x7fffa565ad10 = {0x12a19, 0x12a18, 0x12a17, 0x12a16, 0x12a15, 0x12a14, 0x12a13, 0x12a12, 0x12a11, 0x12a10, 0x12a0f, 0x12a0e, 0x12a0d, 0x12a0c, 0x12a0b}
        fraction = 0.029296875
        filmid = -1
        first_filmid = -1
        last_coll_update = 419754365.09337598
        last_prog_update = 419754365.09415197
        update_interval = 0.59999999999999998
        prev_filename = 0x0
        prev_output = 0x0
        __FUNCTION__ = "_control_import_job_run"
#6  0x00007ffff79aa89b in _control_job_execute (job=job@entry=0x555559109650) at /home/panda/Downloads/darktable/src/control/jobs.c:314
#7  0x00007ffff79ab5f8 in _control_run_job (control=0x5555555f2690) at /home/panda/Downloads/darktable/src/control/jobs.c:333
        job = 0x555559109650
        job = <optimized out>
#8  _control_work (ptr=<optimized out>) at /home/panda/Downloads/darktable/src/control/jobs.c:582
        params = <optimized out>
        control = 0x5555555f2690
        name = "worker 4\000\000\000\000\000\000\000"
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007ffff1ea955a in start_thread (arg=<optimized out>) at pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736737576640, -6298844400708114883, -57864, 11, 140737488329408, 140736729186304, 6298746002452358717, 6298813729094739517}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#10 0x00007ffff1f26a3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by piratenpanda** [comment]
works fine now. Thanks!
