### ISSUE TITLE
Linking error with libraw

### ISSUE THREAD

**Issue by lock042** [darktable-org/darktable#16796]
### Describe the bug

I've been compiling darktable for many years, without any problems. Recently, I had a small problem that prevents me from compiling it. Even on a new machine, I get this error:

```
[31%] Built target raw
[31%] Linking CXX static library libraw_r.a
[31%] Built target raw_r
gmake : *** [Makefile:156 : all] Error 2
```

I'm not very comfortable with `cmake`, which I never use. If you need further information, please let me know.
I've tried compiling with the build script or manually, I get the same error.

I'm on debian testing.

### Steps to reproduce

```
git clone --recurse-submodules --depth 1 https://github.com/darktable-org/darktable.git
cd darktable
./build.sh --prefix /usr/ --build-type Release --install --sudo
```

### Expected behavior

darktable should compile

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

master

### What OS are you using?

Linux

### What is the version of your OS?

debian testing

### Describe your system?

This is a fresh install

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
You need to look for error messages prior to the abort - a build can continue after a fatal error if there are components which do not depend on the one which failed to build.  From what you've shown, libraw in fact built successfully - if the error were in linking libraw, you would have seen an error message specifically about it in those last few lines of output.

**Comment by lock042** [comment]
OH you're right, I've missed something:

```
Traceback (most recent call last):
  File "/home/cyril/.local/bin/jsonschema", line 5, in <module>
    from jsonschema.cli import main
  File "/home/cyril/.local/lib/python3.11/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/home/cyril/.local/lib/python3.11/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/home/cyril/.local/lib/python3.11/site-packages/jsonschema/exceptions.py", line 15, in <module>
    from attrs import define
ModuleNotFoundError: No module named 'attrs'
[ 15%] Building C object bin/cmstest/CMakeFiles/darktable-cmstest.dir/__/version_gen.c.o
gmake[2]: *** [share/darktable/CMakeFiles/validate_wbpresets_json.dir/build.make:72: share/darktable/CMakeFiles/validate_wbpresets_json] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:7527: share/darktable/CMakeFiles/validate_wbpresets_json.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 23%] Built target raw
Traceback (most recent call last):
  File "/home/cyril/.local/bin/jsonschema", line 5, in <module>
    from jsonschema.cli import main
  File "/home/cyril/.local/lib/python3.11/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/home/cyril/.local/lib/python3.11/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/home/cyril/.local/lib/python3.11/site-packages/jsonschema/exceptions.py", line 15, in <module>
    from attrs import define
ModuleNotFoundError: No module named 'attrs'
[ 23%] Linking CXX static library librawspeed.a
gmake[2]: *** [share/darktable/CMakeFiles/validate_noiseprofiles_json.dir/build.make:72: share/darktable/CMakeFiles/validate_noiseprofiles_json] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:7501: share/darktable/CMakeFiles/validate_noiseprofiles_json.dir/all] Error 2
[ 23%] Linking C executable ../darktable-cmstest
[ 31%] Built target raw_r
[ 31%] Built target darktable-cmstest
[ 31%] Built target rawspeed
gmake: *** [Makefile:156: all] Error 2
```
