### ISSUE TITLE
Darktable 2.6.2 crashes on Ubuntu 19.04

### ISSUE THREAD

**Issue by hanswundersam** [darktable-org/darktable#2590]
**Describe the bug**
Darktable 2.6.2 crashes on quite fresh Ubuntu 19.04 install with `an error occurred while trying to execute gdb. Segmentation fault (core dumped)`. There is enough RAM available I believe. If DT shows smaller subfolders only, crash does not happen.

**To Reproduce**
1. Install DT 2.6.2 from official Ubuntu PPA
2. Import folder and subfolders with ~19,000 pictures
3. Scroll down to make DT load many thumbnails
4. See crash

**Expected behavior**
Shouldn't crash

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version 2.6.2
 - Asus UX31A laptop with 4GB RAM

**Backtrace**
```
Reading symbols from darktable...
Reading symbols from /usr/lib/debug/.build-id/ba/5c710ee8bf1731efbc39d99676882863da6547.debug...
(gdb) r
Starting program: /usr/bin/darktable 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef33c700 (LWP 16177)]
[New Thread 0x7fffeeb3b700 (LWP 16178)]
[New Thread 0x7fffee33a700 (LWP 16179)]
[New Thread 0x7fffed5e2700 (LWP 16180)]
[New Thread 0x7fffecde1700 (LWP 16181)]
[New Thread 0x7fffd7fff700 (LWP 16182)]
[New Thread 0x7fffcf7fe700 (LWP 16183)]
[New Thread 0x7fffd77fe700 (LWP 16184)]
[New Thread 0x7fffd6ffd700 (LWP 16185)]
[New Thread 0x7fffd67fc700 (LWP 16186)]
[New Thread 0x7fffd5ffb700 (LWP 16187)]
[New Thread 0x7fffd57fa700 (LWP 16188)]
[New Thread 0x7fffd4ff9700 (LWP 16189)]
[New Thread 0x7fffcffff700 (LWP 16190)]
[New Thread 0x7fffaffff700 (LWP 16191)]
[New Thread 0x7fffaf7fe700 (LWP 16193)]
[New Thread 0x7fffaeffd700 (LWP 16194)]
[New Thread 0x7fffae7fc700 (LWP 16195)]
[Thread 0x7fffeeb3b700 (LWP 16178) exited]
[New Thread 0x7fffeeb3b700 (LWP 16196)]
[Thread 0x7fffeeb3b700 (LWP 16196) exited]
[New Thread 0x7fffeeb3b700 (LWP 16197)]
[Thread 0x7fffeeb3b700 (LWP 16197) exited]
[New Thread 0x7fffeeb3b700 (LWP 16198)]
[Thread 0x7fffeeb3b700 (LWP 16198) exited]
[New Thread 0x7fffeeb3b700 (LWP 16199)]
[Thread 0x7fffeeb3b700 (LWP 16199) exited]
[New Thread 0x7fffeeb3b700 (LWP 16200)]
[New Thread 0x7fffcd774700 (LWP 16201)]
[New Thread 0x7fffccaf6700 (LWP 16202)]
[New Thread 0x7fffad1fb700 (LWP 16203)]
[New Thread 0x7fff7bfff700 (LWP 16204)]
[New Thread 0x7fff7b7fe700 (LWP 16205)]
[New Thread 0x7fff7affd700 (LWP 16206)]
[Thread 0x7fffad1fb700 (LWP 16203) exited]
[Thread 0x7fffcd774700 (LWP 16201) exited]
[New Thread 0x7fffcd774700 (LWP 16207)]
[Thread 0x7fffcd774700 (LWP 16207) exited]
[Thread 0x7fffaffff700 (LWP 16191) exited]
[New Thread 0x7fffaffff700 (LWP 16237)]
[New Thread 0x7fffcd774700 (LWP 16238)]
[New Thread 0x7fffad1fb700 (LWP 16239)]
[New Thread 0x7fff630ec700 (LWP 16240)]
[New Thread 0x7fff628eb700 (LWP 16241)]
[New Thread 0x7fff620ea700 (LWP 16242)]
[New Thread 0x7fff618e9700 (LWP 16243)]
[New Thread 0x7fff610e8700 (LWP 16244)]
[New Thread 0x7fff608e7700 (LWP 16245)]
[New Thread 0x7fff600e6700 (LWP 16246)]
[New Thread 0x7fff71355700 (LWP 16247)]
[New Thread 0x7fff71b56700 (LWP 16248)]
[New Thread 0x7fff70353700 (LWP 16250)]
[New Thread 0x7fff70b54700 (LWP 16249)]
[New Thread 0x7fff6fb52700 (LWP 16251)]
[New Thread 0x7fff5ca03700 (LWP 16252)]
[New Thread 0x7fff7a7fc700 (LWP 16253)]
[New Thread 0x7fff79ffb700 (LWP 16254)]
[New Thread 0x7fff793a8700 (LWP 16255)]
[New Thread 0x7fff783a6700 (LWP 16256)]
[New Thread 0x7fff78ba7700 (LWP 16257)]
[New Thread 0x7fff6bd92700 (LWP 16258)]
[New Thread 0x7fff6b591700 (LWP 16259)]
[Thread 0x7fffcd774700 (LWP 16238) exited]

Thread 12 "worker 7" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd5ffb700 (LWP 16187)]
0x00007ffff784110b in g_slice_free_chain_with_offset ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff784110b in g_slice_free_chain_with_offset () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7e0c3ef in dt_dev_pixelpipe_cleanup_nodes (pipe=0x7fffd5fe9040) at ./src/develop/pixelpipe_hb.c:229
#2  0x00007ffff7e0c43b in dt_dev_pixelpipe_cleanup (pipe=pipe@entry=0x7fffd5fe9040) at ./src/develop/pixelpipe_hb.c:187
#3  0x00007ffff7d54aa5 in dt_imageio_export_with_flags (imgid=<optimised out>, imgid@entry=15667, filename=filename@entry=0x7ffff7f426d5 "unused", format=format@entry=0x7fffd5feb0e0, 
    format_params=format_params@entry=0x7fffd5feafe0, ignore_exif=ignore_exif@entry=1, display_byteorder=display_byteorder@entry=0, high_quality=0, upscale=0, thumbnail_export=1, filter=0x0, 
    copy_metadata=0, icc_type=DT_COLORSPACE_NONE, icc_filename=0x0, icc_intent=DT_INTENT_LAST, storage=0x0, storage_params=0x0, num=1, total=1) at ./src/common/imageio.c:963
#4  0x00007ffff7d711ca in _init_8 (size=DT_MIPMAP_1, imgid=15667, color_space=0x21, iscale=0x7fffa4c98018, height=0x7fffa4c98014, width=0x7fffa4c98010, buf=0x7fffa4c98030 "")
    at ./src/common/mipmap_cache.c:1221
#5  dt_mipmap_cache_get_with_caller (cache=0x55555621bc00, buf=buf@entry=0x7fffd5fec690, imgid=15667, mip=DT_MIPMAP_1, flags=flags@entry=DT_MIPMAP_BLOCKING, mode=mode@entry=114 'r', 
    file=0x7ffff7f4c060 "/build/darktable-xuXDPt/darktable-2.6.2/src/control/jobs/image_jobs.c", line=35) at ./src/common/mipmap_cache.c:801
#6  0x00007ffff7d9bc24 in dt_image_load_job_run (job=<optimised out>) at ./src/control/jobs/image_jobs.c:35
#7  0x00007ffff7d9400d in dt_control_job_execute (job=job@entry=0x55555644f910) at ./src/control/jobs.c:304
#8  0x00007ffff7d94b28 in dt_control_run_job (control=0x5555555996f0) at ./src/control/jobs.c:323
#9  dt_control_work (ptr=<optimised out>) at ./src/control/jobs.c:568
#10 0x00007ffff7a85182 in start_thread (arg=<optimised out>) at pthread_create.c:486
#11 0x00007ffff7bbab1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by hanswundersam** [comment]
Okay, I don't know what the problem was but solved it by copy-pasting the configuration files in ~/.config/darktable from my old installation. Now the segmentation fault is gone and Darktable runs stable. Something in the config creation process must have caused the crash. Not sure if someone would like to investigate this further or just close the issue as solved.

In any case, a huge Thank You to all Darktable developers, you make awesome software!

**Comment by Nilvus** [comment]
@hanswundersam as lot of things will change on next major release and lot of works is done for that, I think that's better to close one. So could you closed it ? Thanks.

**Comment by hanswundersam** [comment]
Sure, thank you. I look forward to the next release! :+1:
