### ISSUE TITLE
Segfault after removing the cache directory

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3134]
When I remove ~/.cache/darktable then darktable segfaults at the first start with the following backtrace:

```
(gdb) bt full
#0  0x00007fff6c27e17f in _mm_load_ps (__P=0x7ffe77a9a000) at /usr/lib64/gcc/x86_64-suse-linux/9/include/xmmintrin.h:927
        input = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        multiplied = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        i = 4256
        alignment = 0
        coeffs = {[0] = 2.26953125, [1] = 1, [2] = 2.26953125, [3] = 1}
        in = 0x7ffe77a9a000
        out = 0x7ffba2314fc0
        j = 3746
        d = 0x7fffd4031470
        roi_out = 0x7fffe2ad2560
        ovoid = 0x7ffb9cca4040
        ivoid = 0x7ffe72429080
        filters = 2492765332
        filters = 1814552165
        xtrans = 0xffffffffffff1ef0
        d = 0xea2d4003400
#1  0x00007fff6c27e17f in process_sse2._omp_fn.1 () at /home/asn/workspace/projects/darktable/src/iop/temperature.c:603
        input = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        multiplied = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        i = 4256
        alignment = 0
        coeffs = {[0] = 2.26953125, [1] = 1, [2] = 2.26953125, [3] = 1}
        in = 0x7ffe77a9a000
        out = 0x7ffba2314fc0
        j = 3746
        d = 0x7fffd4031470
        roi_out = 0x7fffe2ad2560
        ovoid = 0x7ffb9cca4040
        ivoid = 0x7ffe72429080
        filters = 2492765332
        filters = 1814552165
        xtrans = 0xffffffffffff1ef0
        d = 0xea2d4003400
#2  0x00007ffff76fcb36 in  () at /usr/lib64/libgomp.so.1
#3  0x00007ffff7868f2a in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff79814af in clone () at /lib64/libc.so.6```

**Comment by cryptomilk** [comment]
```
541       const float *in = ((float *)ivoid) + (size_t)j * roi_out->width;
```
is pointing to invalid memory.

```
(gdb) bt full
#0  0x00007fff6837e17f in _mm_load_ps (__P=0x7ffe8831a000) at /usr/lib64/gcc/x86_64-suse-linux/9/include/xmmintrin.h:927
        input = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        multiplied = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        i = 608
        alignment = 0
        coeffs = {[0] = 2.26953125, [1] = 1, [2] = 2.26953125, [3] = 1}
        in = 0x7ffe8831a000
        out = 0x7ffdd56bdfc0
        j = 2012
        d = 0x7fffcc096d10
        roi_out = 0x7fffe1ad0560
        ovoid = 0x7ffdd2852040
        ivoid = 0x7ffe854ae080
        filters = 2492765332
        filters = 1748491877
        xtrans = 0xffffffffffff1ef0
        d = 0x7dccc011000
#1  0x00007fff6837e17f in process_sse2._omp_fn.1 () at /home/asn/workspace/projects/darktable/src/iop/temperature.c:603
        input = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        multiplied = {[0] = 0, [1] = 0, [2] = 0, [3] = 0}
        i = 608
        alignment = 0
        coeffs = {[0] = 2.26953125, [1] = 1, [2] = 2.26953125, [3] = 1}
        in = 0x7ffe8831a000
        out = 0x7ffdd56bdfc0
        j = 2012
        d = 0x7fffcc096d10
        roi_out = 0x7fffe1ad0560
        ovoid = 0x7ffdd2852040
        ivoid = 0x7ffe854ae080
        filters = 2492765332
        filters = 1748491877
        xtrans = 0xffffffffffff1ef0
        d = 0x7dccc011000
#2  0x00007ffff76fcb36 in  () at /usr/lib64/libgomp.so.1
#3  0x00007ffff7868f2a in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff79814af in clone () at /lib64/libc.so.6

(gdb) p in
$1 = (const float *) 0x7ffe8831a000
(gdb) p *in
Cannot access memory at address 0x7ffe8831a000
p out
$2 = (float *) 0x7ffdd56bdfc0
(gdb) p *out
$3 = 9.96937982e+17
(gdb) p j
$4 = 2012
(gdb) p *roi_out
$5 = {
  x = 0, 
  y = 0, 
  width = 6048, 
  height = 4024, 
  scale = 1
}
```

**Comment by cryptomilk** [comment]
I can't reproduce it anymore. Mystically fixed!

**Comment by jenshannoschwalm** [comment]
Wait wait! I have observed something like this too but did not understand.

If you force a large number of images to recalculate the thumbnails by any means and then start to develop an image dt sometimes hangs or crashes. I think there might be still some mutex handling missing ...
