### ISSUE TITLE
Invalid image opened if specified on the cmdline

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3536]
**Describe the bug**

```
Starting program: /home/asn/workspace/projects/darktable/obj/src/darktable /home/asn/Pictures/av1-avif/testFiles/Netflix/avif/cosmos_frame01000_yuv420_8bpc_bt709_g22_qlossless.avif
```

I'm trying to open and avif file and it ends up trying to open the first RAW file from the last lighttable view:

```
(gdb) p filename
$2 = 0x7fffe20506a0 "/home/asn/Pictures/RAW/2019/2019-11_Eichhörnchen/2019-11_RAW_Eichhörnchen/2019-11-16__7M37254.ARW"
(gdb) bt      
#0  0x00007ffff7d4665d in read_image (filename=0x7fffe20506a0 "/home/asn/Pictures/RAW/2019/2019-11_Eichhörnchen/2019-11_RAW_Eichhörnchen/2019-11-16__7M37254.ARW", avif=0x7fffe204ffb0) at /home/asn/workspace/projects/darktable/src/common/imageio_avif.c:47 
#1  0x00007ffff7d467f3 in dt_imageio_open_avif (img=0x7fffe2050160, filename=0x7fffe20506a0 "/home/asn/Pictures/RAW/2019/2019-11_Eichhörnchen/2019-11_RAW_Eichhörnchen/2019-11-16__7M37254.ARW", mbuf=0x7fffe2051740) at /home/asn/workspace/projects/darktable/src/common/imageio_avif.c:101
```

**Comment by cryptomilk** [comment]
Oh, the code really tries every open function. So you need a check for the extension and not read the image if it is not meant for you.
