### ISSUE TITLE
Segmentation fault entering darkroom

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6543]
**Describe the bug**
Encountered segfault when entering darkroom. I had edited the image previously (with another master build).
When I restarted darktable after the segfault, I was able to open the image, but its history stack reverted to the default (my work was lost).

Interestingly, the same error also occurred then leaving darkroom (fault seems to be on the same line, at least), see #6495. 

**To Reproduce**
1. Go to lighttable
2. Double-click an image

**Expected behavior**
Image is opened, history is retained.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: e0cff0
 - OS: Ubuntu 20.04 64-bit
 - OpenCL activated
 - Which graphics card and driver version: NVidia 1060, 450.80.02-0ubuntu0.20.04.2

bt full
```
Thread 32 "worker res 0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffefafc700 (LWP 2414)]
dt_interpolation_resample_sse._omp_fn.1 () at /home/kofa/darktable/src/common/interpolation.c:1727
1727              vhs = _mm_add_ps(vhs, _mm_mul_ps(*(__m128 *)&i[baseidx], vhtap));
(gdb) bt full
#0  dt_interpolation_resample_sse._omp_fn.1 () at /home/kofa/darktable/src/common/interpolation.c:1727
        baseidx = 0
        htap = 0.000118000826
        vhtap = {0.000118000826, 0.000118000826, 0.000118000826, 0.000118000826}
        ix = <optimised out>
        vhs = {0, 0, 0, 0}
        vtap = <optimised out>
        vvtap = <optimised out>
        iy = 25
        vs = {0, 0, 0, 0}
        hl = 26
        o = <optimised out>
        ox = 0
        vlidx = <optimised out>
        hlidx = 1
        vl = <optimised out>
        vkidx = <optimised out>
        viidx = <optimised out>
        hkidx = <optimised out>
        hiidx = <optimised out>
        vmeta = <optimised out>
        vkernel = <optimised out>
        vlength = <optimised out>
        vindex = <optimised out>
        hkernel = <optimised out>
        hlength = <optimised out>
        hindex = <optimised out>
        out = <optimised out>
        roi_out = <optimised out>
        out_stride = <optimised out>
        in_stride = <optimised out>
        in = <optimised out>
        __FUNCTION__ = "dt_interpolation_resample"
#1  0x00007ffff784f77e in  () at /lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff79cf609 in start_thread (arg=<optimised out>) at pthread_create.c:477
        ret = <optimised out>
        pd = <optimised out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737214662400, -9101215076684857677, 140736943026190, 140736943026191, 140737346234144, 140737214600768, 9101249581051870899, 9101231835318779571}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#3  0x00007ffff7b0b293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by kofa73** [comment]
Not seen for a while now
