### ISSUE TITLE
sigsegv if reentering darkroom with crop&rotate open

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#7266]
**Describe the bug**
When reentering darkroom for an image which last opened module was clip&rotate, we crash...

**To Reproduce**
1. open an image in darkroom
2. expand clip&rotate module (no need to activate it)
3. return to lighttable
4. reenter darkroom for that image
=> here, it segfault... 100% reproducible

**Expected behavior**
no crash ;)

**Platform (please complete the following information):**
 - Darktable Version: master (https://github.com/darktable-org/darktable/commit/611c61649e7379da79f80eeca10d47e70f99f510)
 - OS: xubuntu 20.04
 - with and without opencl
 - with raw and jpeg (same backtrace)
 - with clean install, fresh config dir and lib, virgin images (just imported with no xmp)

**Additional context**
Backtrace : 
```
(gdb) bt full
#0  0x00007fffb334e222 in gui_update (self=<optimized out>) at /media/docs/dt_aldric/src/iop/rawprepare.c:730
        i = <optimized out>
        g = 0x0
        p = 0x5555578233f0
#1  0x00007ffff7d44ea4 in dt_iop_gui_update (module=0x555559be5910) at /media/docs/dt_aldric/src/develop/imageop.c:1973
#2  0x00007ffff7d396b8 in dt_dev_pop_history_items (dev=0x5555565c84e0, cnt=5) at /media/docs/dt_aldric/src/develop/develop.c:1237
        module = <optimized out>
        dev_iop = 
          0x555559223240 = {0x555559be5910, 0x555558f42f60, 0x555558c924a0, 0x5555582f3c00, 0x555559664b90, 0x555559b926f0, 0x55555720c5b0, 0x555558235e00, 0x5555583263b0, 0x555558320820, 0x55555974aa00, 0x555558ceb400, 0x5555591c5b90, 0x555557ab5000, 0x555559574870, 0x555558670a40, 0x555558a70800, 0x5555577e6290, 0x55555776c3a0, 0x55555848e800, 0x555557d62000, 0x55555859d000, 0x555559985800, 0x555558b77800, 0x555559c11ba0, 0x555557c60b80, 0x5555576f9940, 0x555558f25800, 0x55555908b390, 0x555558245800, 0x5555579fcb80, 0x555557d71590, 0x555557afd000, 0x5555596c2780, 0x555557c34000, 0x555558d72800, 0x555557ca2c00, 0x55555786b970, 0x555559157b90, 0x55555887b000, 0x555558e15780, 0x555557d0cc00, 0x555558005b80, 0x55555991c000, 0x5555581eb200, 0x555558fc0780, 0x55555871b000, 0x555558262000, 0x5555590d1170, 0x555557f8d800, 0x55555889e800, 0x555558ff9410, 0x55555950eba0, 0x555557d80400, 0x55555869c000, 0x555558a3b1c0, 0x5555593bab90, 0x555558e86800, 0x5555586f2c00, 0x55555842c000, 0x555559859b90, 0x555558d3eba0, 0x5555583a1000, 0x555559bc0f10, 0x555558520f70, 0x555559533a60, 0x555559577ba0, 0x555558572b90, 0x555558e06800, 0x5555596c8000, 0x555557f99000, 0x555559414400, 0x5555595137a0, 0x555558f31b90, 0x555558244b80, 0x555559752150, 0x555559302650, 0x555559a39000, 0x555557ff53a0}
        modules = 
          0x555557dfac40 = {0x555559be5910, 0x555558f42f60, 0x555558c924a0, 0x5555582f3c00, 0x555559664b90, 0x555559b926f0, 0x55555720c5b0, 0x555558235e00, 0x5555583263b0, 0x555558320820, 0x55555974aa00, 0x555558ceb400, 0x5555591c5b90, 0x555557ab5000, 0x555559574870, 0x555558670a40, 0x555558a70800, 0x5555577e6290, 0x55555776c3a0, 0x55555848e800, 0x555557d62000, 0x55555859d000, 0x555559985800, 0x555558b77800, 0x555559c11ba0, 0x555557c60b80, 0x5555576f9940, 0x555558f25800, 0x55555908b390, 0x555558245800, 0x5555579fcb80, 0x555557d71590, 0x555557afd000, 0x5555596c2780, 0x555557c34000, 0x555558d72800, 0x555557ca2c00, 0x55555786b970, 0x555559157b90, 0x55555887b000, 0x555558e15780, 0x555557d0cc00, 0x555558005b80, 0x55555991c000, 0x5555581eb200, 0x555558fc0780, 0x55555871b000, 0x555558262000, 0x5555590d1170, 0x555557f8d800, 0x55555889e800, 0x555558ff9410, 0x55555950eba0, 0x555557d80400, 0x55555869c000, 0x555558a3b1c0, 0x5555593bab90, 0x555558e86800, 0x5555586f2c00, 0x55555842c000, 0x555559859b90, 0x555558d3eba0, 0x5555583a1000, 0x555559bc0f10, 0x555558520f70, 0x555559533a60, 0x555559577ba0, 0x555558572b90, 0x555558e06800, 0x5555596c8000, 0x555557f99000, 0x555559414400, 0x5555595137a0, 0x555558f31b90, 0x555558244b80, 0x555559752150, 0x555559302650, 0x555559a39000, 0x555557ff53a0}
        dev_iop_changed = <optimized out>
#3  0x00007ffff7d3b60a in dt_dev_invalidate_from_gui (dev=<optimized out>) at /media/docs/dt_aldric/src/develop/develop.c:2326
#4  0x00007ffff7d40ee1 in dt_iop_request_focus (module=0x555558a70800) at /media/docs/dt_aldric/src/develop/imageop.c:2100
        iop_w = <optimized out>
        context = <optimized out>
#5  0x00007ffff7d40fc2 in dt_iop_gui_set_single_expanded (module=0x555558a70800, expanded=1) at /media/docs/dt_aldric/src/develop/imageop.c:2143
        var = "\300^hUUU\000\000&\324k\367\377\177\000\000\000\000\000\000\000\000\000\000\300^hUUU\000\000@\021fUUU\000\000@\021fUUU\000\000\001\000\000\000\000\000\000\000\223ԟ\366\377\177\000\000p\314\377\377\377\177\000\000\220?hUUU", '\000' <repeats 11 times>, "\314\377\377\377\177\000\000\000\000\000\000\000\000\000\000\300\215\376XUU\000\000\356U\003", '\000' <repeats 13 times>, "\260\314\377\377\377\177\000\000\060\314\377\377\377\177\000\000\260\331\377\377\001\000\000\000@\033*YUU\000\000\000\000\000\000\000\000\000\000\064\000\000\000\377\177\000\001\000\000\000\000\000\000\000\000 \314\377\377\377\177\000\000\260\331\377\377\377\177\000\000\360"...
#6  0x00007ffff7d4110a in dt_iop_gui_set_single_expanded (expanded=<optimized out>, module=<optimized out>) at /media/docs/dt_aldric/src/develop/imageop.c:2196
#7  dt_iop_gui_set_expanded (module=<optimized out>, expanded=<optimized out>, collapse_others=<optimized out>) at /media/docs/dt_aldric/src/develop/imageop.c:2196
#8  0x0000555555661140 in  ()
#9  0x0000555555661140 in  ()
#10 0x2f736e6967756c70 in  ()
#11 0x6d6f6f726b726164 in  ()
#12 0x6e697070696c632f in  ()
#13 0x646e617078652f67 in  ()
#14 0x0064006400006465 in  ()
#15 0x00007fffff000064 in  ()
#16 0x0000000000000000 in  ()
```

**Comment by wpferguson** [comment]
Crashes for me too

**Comment by TurboGit** [comment]
Fixed !

**Comment by wpferguson** [comment]
Thanks @TurboGit!
