### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#7852]
**Describe the bug**
On current Fedora 33 with all updates the integration tests for dt master fail.
This worked ~3weeks ago

**To Reproduce**
```
[hanno@fedora-w580 integration]$ ./run.sh
Test 0000-nop
      Image mire1.cr2
      CPU & GPU version differ by 66891 pixels
Traceback (most recent call last):
  File "/home/hanno/sources/darktable/src/tests/integration/0000-nop/../deltae", line 32, in <module>
    delta_E = colour.delta_E(expected_lab, output_lab, method="CIE 2000")
  File "/home/hanno/.local/lib/python3.9/site-packages/colour/difference/__init__.py", line 161, in delta_E
    return function(a, b, **filter_kwargs(function, **kwargs))
  File "/home/hanno/.local/lib/python3.9/site-packages/colour/difference/delta_e.py", line 305, in delta_E_CIE2000
    l_bar_prime = 0.5 * (L_1 + L_2)
ValueError: operands could not be broadcast together with shapes (1364,2048) (2602,3908) 
  OK
```

**Platform**
 - Darktable todays master
 - OS: Fedora 33 x64
 - OpenCL activated -- yes
 - quadro rtx4000, 460

**Additional context**
python 3.9.1, dependencies installed.

**Comment by jenshannoschwalm** [comment]
Latest python fedora updates fixes this

**Comment by TurboGit** [comment]
Or maybe the change in deltae recently merged? We do not depends on Python3 colour module based on OpenCL.
