### ISSUE TITLE
free(): invalid pointer.  Aborted (core dumped)

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8056]
Current master  darktable 3.5.0+891~gc672080f5
WSL Ubuntu 20.04

In culling view with focus peaking on.
Was doing a ctrl+w on images in this view and after some time DT crashed.

The terminal had this info

```
free(): invalid pointer
Aborted (core dumped)
```

**Comment by chhil** [comment]
Reproducible.

Resuming culling from the last point before it crashed, crashes after second ctrl+w in culling.

**Comment by chhil** [comment]
Ran it in the vscode debugger....

@ralfbrown 


![image](https://user-images.githubusercontent.com/1119439/106406358-0c8a6800-645f-11eb-9d32-2b021b04784e.png)


```
libdarktable.so!blur_vertical_1ch_sse(__m128 * const restrict scratch, const int radius, const int width, const int height, float * const restrict buf) (\home\mchhil\darktable\src\common\box_filters.c:344)
libdarktable.so!blur_vertical_4wide(float * const restrict buf, const size_t height, const size_t width, const size_t radius, float * const restrict scratch) (\home\mchhil\darktable\src\common\box_filters.c:498)
libdarktable.so!blur_vertical_1ch._omp_fn.0() (\home\mchhil\darktable\src\common\box_filters.c:638)
libgomp.so.1!GOMP_parallel (Unknown Source:0)
libdarktable.so!blur_vertical_1ch(const size_t eff_height, float * const restrict scanlines, const size_t radius, const size_t width, const size_t height, float * const restrict buf) (\home\mchhil\darktable\src\common\box_filters.c:788)
libdarktable.so!box_mean_2ch(const unsigned int iterations, const int radius, const size_t width, const size_t height, float * const restrict in) (\home\mchhil\darktable\src\common\box_filters.c:788)
libdarktable.so!dt_box_mean(float * const buf, const size_t height, const size_t width, const int ch, const int radius, const unsigned int iterations) (\home\mchhil\darktable\src\common\box_filters.c:813)
libdarktable.so!fast_surface_blur(float * const restrict image, const size_t width, const size_t height, const int radius, float feathering, const int iterations, const dt_iop_guided_filter_blending_t filter, const float quantization, const float quantize_min, const float quantize_max, const float scale) (\home\mchhil\darktable\src\common\fast_guided_filter.h:344)
libdarktable.so!dt_focuspeaking(int width, int height, const int buf_height, const int buf_width, uint8_t * const restrict image, cairo_t * cr) (\home\mchhil\darktable\src\common\focus_peaking.h:108)
libdarktable.so!dt_view_image_get_surface(int imgid, int width, int height, cairo_surface_t ** surface, const gboolean quality) (\home\mchhil\darktable\src\views\view.c:1073)
libdarktable.so!_event_image_draw(cairo_t * cr, gpointer user_data, GtkWidget * widget) (\home\mchhil\darktable\src\dtgtk\thumbnail.c:577)
libdarktable.so!_event_image_draw(GtkWidget * widget, cairo_t * cr, gpointer user_data) (\home\mchhil\darktable\src\dtgtk\thumbnail.c:479)
libgtk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libgobject-2.0.so.0!g_signal_emit_valist (Unknown Source:0)
libgobject-2.0.so.0!g_signal_emit (Unknown Source:0)
libgtk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libgtk-3.so.0!gtk_container_propagate_draw (Unknown Source:0)
libgtk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libgtk-3.so.0!gtk_container_propagate_draw (Unknown Source:0)
libgtk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
```

**Comment by ralfbrown** [comment]
Unable to reproduce....  The two crashes you report are different - the first one was due to overrunning a buffer and corrupting malloc housekeeping info (found by a possibly much later free() call), the second is a bad pointer during a read.

Does the crash persist if you disable the SSE codepath? (`--conf codepaths/sse2=false`)

**Comment by chhil** [comment]
Do I run DT with following line as command line param?
`--conf codepaths/sse2=false`

Currently to avoid the crash, I turn off focus peaking before I do a ctrl+w to zoom in.

**Comment by ralfbrown** [comment]
Yes, that parameter was my suggestion to help narrow down the issue (is it specific to the SSE path or more general to the inputs to `blur_vertical_4wide`).  It may not be an acceptable workaround as some of the modules are still substantially slower without SSE.

**Comment by chhil** [comment]
I haven't seen a crash with the command line param after some usage.

**Comment by chhil** [comment]
And just as I restarted DT again with the the command line param and tried doing a ctrl+w

This time I got a backtrace though.

[darktable_bt_YVQ1X0.txt](https://github.com/darktable-org/darktable/files/5902037/darktable_bt_YVQ1X0.txt)


```
warning: Currently logging to /tmp/darktable_bt_YVQ1X0.txt.  Turn the logging off and on to make the new setting effective.
#0  0x00007f6d40d95dff in __GI___wait4 (pid=pid@entry=13043, stat_loc=stat_loc@entry=0x0, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f6d40d95d7b in __GI___waitpid (pid=pid@entry=13043, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at waitpid.c:38
#2  0x00007f6d4101af70 in _dt_sigsegv_handler (param=11) at /home/mchhil/darktable/src/common/system_signal_handling.c:114
#3  0x00007f6d40cf6210 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f6d40f5b4eb in load_add_4wide (values=0x7fffcbe1f000, accum=<optimized out>, out=0x7fffcbd74900) at /home/mchhil/darktable/src/common/box_filters.c:175
#5  blur_vertical_4wide (buf=buf@entry=0x7fffcbcdbc00, height=height@entry=2, width=width@entry=8, radius=radius@entry=3, scratch=scratch@entry=0x7fffcbd74900) at /home/mchhil/darktable/src/common/box_filters.c:538
#6  0x00007f6d40f5dd1a in dt_box_mean_4ch (iterations=1, radius=3, width=3, height=0, buf=0x7fffcbcdbc00) at /home/mchhil/darktable/src/common/box_filters.c:705
#7  dt_box_mean (buf=buf@entry=0x7fffcbcdbc00, height=height@entry=2, width=width@entry=2, ch=ch@entry=4, radius=radius@entry=3, iterations=iterations@entry=1) at /home/mchhil/darktable/src/common/box_filters.c:809
#8  0x00007f6d411a3bc2 in variance_analyse (guide=guide@entry=0x7fffcbbf5a00, mask=mask@entry=0x7fffcbbc0400, ab=ab@entry=0x7fffcbc46380, width=width@entry=2, height=height@entry=2, radius=radius@entry=3, feathering=feathering@entry=9.99999975e-06) at /home/mchhil/darktable/src/common/fast_guided_filter.h:203
#9  0x00007f6d411a6010 in fast_surface_blur (image=0x7fffc973e240, width=8, height=8, radius=<optimized out>, feathering=9.99999975e-06, iterations=4, filter=DT_GF_BLENDING_LINEAR, quantization=0, quantize_min=0.00390625, quantize_max=1, scale=<optimized out>) at /home/mchhil/darktable/src/common/fast_guided_filter.h:341
#10 0x00007f6d411ab5ec in dt_focuspeaking (width=986, height=986, buf_height=8, buf_width=8, image=0x7fffcbcefe40 "\377\377\377\377\367\377\377\377\377\377\377\377\371\377\377\377", cr=0x7fffcafb5a30) at /home/mchhil/darktable/src/common/focus_peaking.h:108
#11 dt_view_image_get_surface (imgid=24553, width=2506, height=986, surface=surface@entry=0x7fffd0151580, quality=quality@entry=0) at /home/mchhil/darktable/src/views/view.c:1073
#12 0x00007f6d4113e840 in _event_image_draw (cr=0x7fffca256500, user_data=0x7fffcbc216b0, widget=<optimized out>) at /home/mchhil/darktable/src/dtgtk/thumbnail.c:577
#13 0x00007f6d4113f64e in _event_image_draw (widget=<optimized out>, cr=<optimized out>, user_data=<optimized out>) at /home/mchhil/darktable/src/dtgtk/thumbnail.c:479
```

**Comment by ralfbrown** [comment]
OK, the immediate cause is radius>height, which makes (height-radius) wrap to a huge number in the loop at lines 534-540.
For some reason, the focus peaking is being called on an 8x8 pixel image, which after downsampling invokes a radius 3 blur on a 2x2 pixel area.  Will look at things in more detail tonight.

**Comment by pd1986** [comment]
I encountered the same issue in my Gentoo. Same error info after running Darktable in terminal. What I do to reproduce the issue is only to click"Darkroom" and then click  "Lighttable", thus application shutdown abruptly and error appears. Does anyone has any idea how to fix it? Thanks.

**Comment by wsyxbcl** [comment]
> I encountered the same issue in my Gentoo. Same error info after running Darktable in terminal. What I do to reproduce the issue is only to click"Darkroom" and then click "Lighttable", thus application shutdown abruptly and error appears. Does anyone has any idea how to fix it? Thanks.

Same issue here, have you figured it out?

**Comment by pd1986** [comment]
> > I encountered the same issue in my Gentoo. Same error info after running Darktable in terminal. What I do to reproduce the issue is only to click"Darkroom" and then click "Lighttable", thus application shutdown abruptly and error appears. Does anyone has any idea how to fix it? Thanks.
> 
> #8695 might be related

Seems to be the same issue. Thanks. I will keep an eye on the update.
