### ISSUE TITLE
[3.4.1] darktable: vsnprintf(): darktable killed by SIGSEGV

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#8595]
Fedora package maintainer here. I am reporting here a bugreport from a user:
You can find all details at
https://bugzilla.redhat.com/show_bug.cgi?id=1945769

Short extract of backtrace:
```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/darktable'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f416201e3e4 in __GI__IO_default_xsputn (f=0x7f41367fe5a0, data=0x7f4118652007, n=23) at genops.c:371
371	genops.c: No such file or directory.
[Current thread is 1 (Thread 0x7f4136ffd640 (LWP 70785))]

Thread 1 (Thread 0x7f4136ffd640 (LWP 70785)):
#0  0x00007f416201e3e4 in __GI__IO_default_xsputn (f=0x7f41367fe5a0, data=0x7f4118652007, n=23) at genops.c:371
        s = 0x7f4118652007 "process slideshow image"
        more = 23
        count = <optimized out>
        p = <optimized out>
        i = <optimized out>
#1  0x00007f4162006759 in outstring_func (done=0, length=23, string=0x7f4118652007 "process slideshow image", s=0x7f41367fe5a0) at ../libio/libioP.h:948
        __PRETTY_FUNCTION__ = "outstring_func"
#2  __vfprintf_internal (s=s@entry=0x7f41367fe5a0, format=format@entry=0x7f4118652007 "process slideshow image", ap=ap@entry=0x7f41367fe720, mode_flags=mode_flags@entry=2) at vfprintf-internal.c:1404
        string_ = 0x7f4118652007
        _buffer = {__routine = 0x7f4118652007, __arg = 0x0, __canceltype = 3432, __prev = 0x0}
        _avail = <optimized out>
        thousands_sep = <optimized out>
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        done = 0
        f = 0x7f411865201e ""
        lead_str_end = 0x7f411865201e ""
        end_of_spec = <optimized out>
        work_buffer = "\036 e\030A\177", '\000' <repeats 34 times>, "x\344\001bA\177\000\000\v", '\000' <repeats 15 times>, "\036 e\030A\177\000\000 \000\026bA\177\000\000@\347\177\066A\177\000\000\377\000\000\000\000\000\000\000\027\000\000\000\000\000\000\000\a e\030A\177\000\000\300\350\177\066A\177\000\000Yg\000bA\177\000\000\a e\030A\177\000\000\000\000\000\000\000\000\000\000h\r", '\000' <repeats 22 times>, "\020\000\000\000\060\000\000\000\340\350\177\066A\177\000\000\020\350\177\066A\177\000\000\000\000\000\000\000\000\000\000"...
        workend = <optimized out>
        ap_save = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7f41367fe810, reg_save_area = 0x7f41367fe740}}
        nspecs_done = 0
        save_errno = 11
        readonly_format = 0
        do_longlong_number = <optimized out>
        __result = <optimized out>
```

**Comment by parafin** [comment]
I've looked at backtrace and I have no idea why vsnprintf call would segfault there.

**Comment by johnny-bit** [comment]
Now that I think about it... I think that this and #7590 might be connected - both are sigsegv in slideshow with hard reproducer.
