### ISSUE TITLE
01c98a0bb introduced segfault on startup

### ISSUE THREAD

**Issue by matze** [darktable-org/darktable#9352]
**Describe the bug/issue**

Darktable master crashes since 01c98a0bb on startup.

From the backtrace the relevant flow from crashing thread (I left out the `<optimized out>` and irrelevant crash handler parts):
```
#4  invalid_name (name=0x4 <error: Cannot access memory at address 0x4>) at ../sysdeps/posix/opendir.c:89
#5  __opendir (name=0x4 <error: Cannot access memory at address 0x4>) at ../sysdeps/posix/opendir.c:89
#6  0x00007f54fc4786ef in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f54fc47875d in g_dir_open () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f54fcaf5ee0 in _film_recursive_get_files (path=path@entry=0x4 <error: Cannot access memory at address 0x4>, recursive=0, result=result@entry=0x7f54d3ff0208) at /home/matthias/projects/dev/darktable/src/control/jobs/film_jobs.c:154
#9  0x00007f54fcaf65c1 in _film_import1 (job=job@entry=0x560eb585a9c0, film=film@entry=0x0, images=<optimized out>) at /home/matthias/projects/dev/darktable/src/control/jobs/film_jobs.c:237
        message = "worker %d", '\000' <wiederholt 23 Mal>, "`UUUUU\345\277\000\000\000\000\000\000\000\000NUY\231\231\231\351?\000\000\000\000\000\000\000\000\351EH\233[I\362\277", '\000' <wiederholt 12 Mal>, "\300\377\337@\000\000\000\000\300\377\337@", '\000' <wiederholt 32 Mal>, "worker %d", '\000' <wiederholt 23 Mal>, "`UUUUU\345\277\000\000\000\000\000\000\000\000NUY\231\231\231\351?\000\000\000\000\000\000\000\000\351EH\233[I\362\277"...
#10 0x00007f54fcaf6643 in _pathlist_import_run (job=0x560eb585a9c0) at /home/matthias/projects/dev/darktable/src/control/jobs/film_jobs.c:85
        params = 0x560eb5859330
#11 0x00007f54fcaed4aa in dt_control_job_execute (job=job@entry=0x560eb585a9c0) at /home/matthias/projects/dev/darktable/src/control/jobs.c:300
#12 0x00007f54fcaee048 in dt_control_run_job (control=0x560eb2a9c2f0) at /home/matthias/projects/dev/darktable/src/control/jobs.c:319
        job = 0x560eb585a9c0
        params = <optimized out>
        control = 0x560eb2a9c2f0
        name = "worker 6\000\000\000\000\000\000\000"
#13 dt_control_work (ptr=<optimized out>) at /home/matthias/projects/dev/darktable/src/control/jobs.c:564
        params = <optimized out>
        control = 0x560eb2a9c2f0
        name = "worker 6\000\000\000\000\000\000\000"
```
So basically, `g_dir_open()` is called with a string pointing to `0x4` …

**Comment by TurboGit** [comment]
Fixed.
