### ISSUE TITLE
Renaming Modules crashes DT 3.7.0+114~g147025318-dirty

### ISSUE THREAD

**Issue by waxhead** [darktable-org/darktable#9380]
Hi,

Lastest git pull from today for me  3.7.0+114~g147025318-dirty  has a crash when renaming a module.

gdb output attached.

I have tested this with trying to name a few modules.

[gdb-darktable.txt](https://github.com/darktable-org/darktable/files/6757854/gdb-darktable.txt)

**Comment by johnny-bit** [comment]
Confirmed. Just rename the module and dt will crash.

Your backtrace is weird, because the important backtrace is at the end of the file. Here's the relevant stuff from my backtrace:

```
#0  0x00007fef776a05d7 in wait4 () at /lib64/libc.so.6
#1  0x00007fef7d00efe0 in _dt_sigsegv_handler (param=11) at /home/johnny/darktable_repos/darktable/src/common/system_signal_handling.c:114
#2  0x00007fef776127d0 in <signal handler called> () at /lib64/libc.so.6
#3  0x00007fef7c798754 in gtk_widget_unparent () at /usr/lib64/libgtk-3.so.0
#4  0x00007fef7c517b37 in gtk_box_remove () at /usr/lib64/libgtk-3.so.0
#5  0x00007fef7bdef79a in g_cclosure_marshal_VOID__OBJECTv () at /usr/lib64/libgobject-2.0.so.0
#6  0x00007fef7bdec771 in _g_closure_invoke_va () at /usr/lib64/libgobject-2.0.so.0
#7  0x00007fef7be0461d in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#8  0x00007fef7be0481f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#9  0x00007fef7c563d65 in gtk_container_remove () at /usr/lib64/libgtk-3.so.0
#10 0x00007fef7c78f6d4 in gtk_widget_dispose () at /usr/lib64/libgtk-3.so.0
#11 0x00007fef7bdf27c9 in g_object_run_dispose () at /usr/lib64/libgobject-2.0.so.0
#12 0x00007fef7d098578 in _rename_module_key_press (entry=0x55f782df8d90, event=<optimized out>, module=0x55f785959a20) at /home/johnny/darktable_repos/darktable/src/develop/imageop.c:878
#13 0x00007fef7c7dbe77 in _gtk_marshal_BOOLEAN__BOXED () at /usr/lib64/libgtk-3.so.0
#14 0x00007fef7bdec558 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#15 0x00007fef7bdfdf0c in signal_emit_unlocked_R.isra.0 () at /usr/lib64/libgobject-2.0.so.0
#16 0x00007fef7be03df2 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#17 0x00007fef7be0481f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#18 0x00007fef7c785a94 in gtk_widget_event_internal.part () at /usr/lib64/libgtk-3.so.0
#19 0x00007fef7d12b60c in dt_shortcut_dispatcher (user_data=<optimized out>, event=0x55f783446e70, w=0x55f781a68290) at /home/johnny/darktable_repos/darktable/src/gui/accelerators.c:2632
#20 dt_shortcut_dispatcher (w=0x55f781a68290, event=0x55f783446e70, user_data=<optimized out>) at /home/johnny/darktable_repos/darktable/src/gui/accelerators.c:2608
#21 0x00007fef7c7dbe77 in _gtk_marshal_BOOLEAN__BOXED () at /usr/lib64/libgtk-3.so.0
#22 0x00007fef7bdec558 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#23 0x00007fef7bdfdf0c in signal_emit_unlocked_R.isra.0 () at /usr/lib64/libgobject-2.0.so.0
#24 0x00007fef7be03df2 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#25 0x00007fef7be0481f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#26 0x00007fef7c785937 in gtk_widget_event_internal.part () at /usr/lib64/libgtk-3.so.0
#27 0x00007fef7c6393c1 in propagate_event () at /usr/lib64/libgtk-3.so.0
#28 0x00007fef7c63af03 in gtk_main_do_event () at /usr/lib64/libgtk-3.so.0
#29 0x00007fef7c324515 in _gdk_event_emit () at /usr/lib64/libgdk-3.so.0
#30 0x00007fef7c358232 in gdk_event_source_dispatch () at /usr/lib64/libgdk-3.so.0
#31 0x00007fef7cbfb6a0 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#32 0x00007fef7cbfbb98 in g_main_context_iterate.constprop () at /usr/lib64/libglib-2.0.so.0
#33 0x00007fef7cbfbe8b in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#34 0x00007fef7c639f55 in gtk_main () at /usr/lib64/libgtk-3.so.0
#35 0x00007fef7d131a6d in dt_gui_gtk_run (gui=<optimized out>) at /home/johnny/darktable_repos/darktable/src/gui/gtk.c:1424
#36 0x000055f77ef010a0 in main (argc=<optimized out>, argv=<optimized out>) at /home/johnny/darktable_repos/darktable/src/main.c:93
```

**Comment by dterrahe** [comment]
@waxhead Thanks for reporting!

**Comment by waxhead** [comment]
Thanks for fixing it so quick!  :)

Confirmed working here on Manjaro.  I realised I did leave out a bit of info in my original report.
